#!/bin/bash
#
#Kolmnurga pindala arvutamine
#
#skripti algus
#
echo
echo -n "Sisesta a külje väärtus:"
read a
echo -n "Sisesta b külje väärtus:"
read b
echo -n "Sisesta c külje väärtus:"
read c
#
#Arvutamine
#
p=`echo "scale=2;($a+$b+$c)/2"|bc`  #võtab numberid ülevalt reast 
s=`echo "scale=2;sqrt($p*($p-$a)*($p-$b)*($p-$c))" |bc` #pindala arvutamine
echo "Pindala =$s"
#
#
